// This file is generated by FlutterFire CLI
// File generated from: https://console.firebase.google.com/
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your-web-api-key',
    appId: 'your-web-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    authDomain: 'your-project-id.firebaseapp.com',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDgJdCE77KJsdl0BlHluam-l4iaAx1AUc',
    appId: '1:679415770760:android:54c7000c035179fa2e393d',
    messagingSenderId: '679415770760',
    projectId: 'my-chat-app-dc6d6',
    storageBucket: 'my-chat-app-dc6d6.firebasestorage.app',
  );

  // Initialize Firebase
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeuE_EZ6dvZ46ppTiXHQlYYAmHGoblENo',
    appId: '1:797191789316:ios:688512b4432e4add738e51',
    messagingSenderId: '797191789316',
    projectId: 'crowds-828e4',
    storageBucket: 'crowds-828e4.firebasestorage.app',
    iosBundleId: 'com.etlaq.sagrapp',
  );
}
