const Map<String, String> ar = {
  "wrraqoon": "وراقون",
  "Home": "الرئيسية",
  "Favorite": "المفضلة",
  "My Orders": "طلباتي",
  "More": "المزيد",
  "login": "تسجيل الدخول",
  "signup": "تسجيل جديد",
  "welcome": "مرحباً",
  'login_first': 'من فضلك، قم بتسجيل الدخول اولا.',
  'forgot_password': "هل نسيت كلمة المرور؟",
  'forgot_password_title': "نسيت كلمة المرور",
  "phone": "رقم الجوال",
  "password": "كلمة المرور",
  "confirm_password": "تأكيد كلمة المرور ",
  "wrong": "حدث خطأ ما، من فضلك حاول مره اخري",
  'phone_or_password_incorrect': "رقم الجوال او كلمة المرور غير صحيحة",
  'enter_phone': 'من فضلك،ادخل رقم الهاتف لإستعادة كلمة المرور.',
  'verification_code': 'التحقق من كود التفعيل',
  'enter_verification_code': 'ادخل كود التفعيل المرسل لرقم الهاتف ',
  'reset_passwors': 'إستعادة كلمة المرور',
  'register': 'تسجيل حساب جديد',
  'enter_your_data': 'ادخل بيانات النموذج لتسجيل الحساب',
  'name': "الاسم",
  'enter_name': 'ادخل الاسم بالكامل ',
  'email': "البريد الإلكتروني",
  'enter_email': 'ادخل البريد الإلكتروني',
  'male': 'ذكر',
  'female': 'انثي',
  'gender': 'النوع',
  "enter_password": "ادخل كلمة المرور",
  'dnot_have_an_account': "لا تمتلك حساب ؟ إنشاء حساب جديد",
  'field_required': "هذا الحقل إجباري",
  "phone_short": "رقم الهاتف يجب الا يقل عن ١٠ ارقام",
  "phone_field_required": "رقم الجوال إجباري!",
  "Create Account": "إنشاء حساب",
  "App Language": "لغة التطبيق",
  "Save Changes": "حفظ التغييرات",
  "Please select the language you want": "من فضلك قم بتحديد اللغة التي تريدها",
  "Shopping Cart": "سلة المشتريات",
  "Order Details": "تفاصيل الطلب",
  "Order Summary": "ملخص الطلب",
  "Checkout": "إتمام الشراء",
  "Total": "الإجمالي",
  "Shipping": "الشحن",
  "Discount": "الخصم",
  "Final Total": "الإجمالي النهائي",
  "Invoice Details": "تفاصيل الفاتورة",
  "Product Details": "تفاصيل المنتج",
  "Product Description": "وصف المنتج",
  "Product Attributes": "مواصفات المنتج",
  "Comments": "التعليقات",
  "Add To Cart": "أضف للسلة",
  "Customers": "العملاء",
  "Points": "النقاط",
  "Settings": "الإعدادات",
  "Points Settings": "إعدادات النقاط",
  "Customer Details": "تفاصيل العميل",
  "Edit Account": "تعديل حسابي",
  "Edit Account Information": "تعديل بيانات الحساب",
  "Logout": "تسجيل الخروج",
  "Success": "نجاح",
  "Success Message": "تم تسجيل الدخول بنجاح",
  "Change Password": "تغيير كلمة المرور",
  'change_password_caption': "قم بغيير كلمة المرور",
  'Confirm': "تأكيد",
  'name_field_required': "الاسم مطلوب",
  'name_short': "الاسم قصيرللغايه",
  "Registeration Completed Successfully": "تم تسجيل الحساب بنجاح",
  'collect': "مستلمة",
  'recover': "مرتجعة",
  "Gifts": "الهدايا",
  'password_short': "كلمة  المرور  قصيرة",
  "Welcome Back": "مرحباً بعودتك",
  "Enter your email and password to sign in to your account":
      "ادخل بزيدك الإلكتروني وكملة المرور \n للدخول لحسابك",
  "Email / Phone Number": "البريد الالكتروني / رقم الهاتف",
  "Password": "كلمة المرور",
  "Remember Me": "تذكرني",
  "Forget password ?": "هل نسيت كلمة المرور؟",
  "OR": "أو",
  "Log in": "تسجيل الدخول",
  "Log in by gmail": "تسجيل الدخول بحساب Gmail",
  "Log in by Apple": "تسجيل الدخول بحساب ابل",
  "Don’t have an account? ": " ليس لديك حساب؟",
  "create account": "إنشاء حساب جديد",
  'today': "To Day",
  "Enter Email or phone": "أدخل البريد الإلكتروني او رقم الهاتف",
  "Field Required": "الحقل إجباري",
  "Already have an account?": "هل لديك حساب بالفعل؟",
  "Login": "تسجيل الدخول",
  "Enter your information to register": "ادخل بيانات لإنشاء حساب جديد",
  "By signing up, I agree with the ": "بالتسجيل، أنا أوافق علي ",
  "Terms of Use  & Privacy Policy": "شروط الاستخدام وسياسة الخصوصية",

  // Create An Account Translations

  "First Name": "الأسم الأول",
  "Middle Name": "الأسم الثاني",
  "Family Name": "أسم العائلة",
  "Bank Account Name": "الاسم كما هو موضح بالحساب البنكي",
  "Phone Number": "رقم الجوال",
  "Iban Number": "رقم الايبان",
  "National Number": "رقم الهوية",
  "Marital Status": "الحالة الإجتماعية",
  "Search Country": "البحث عن الدولة",
  "Select Birth Date": "إختار تاريخ الميلاد",
  "Region": "مكان الاقامة",
  "Education Level": "المستوي الدراسي",
  "Job Status": "الحالة الوظيفية",
  "Languages": "اللغات",
  "Profile": "حسابي",
  "Personal Info": "حسابي",
  "Advertisements": "الإعلانات",
  "Previous Events": "الفعاليات السابقة",
  "My Events": "فعاليتي",
  "Orders Under Processing": "طلبات قيد الاجراء",
  "My Commissions": "عمولاتي",
  "Track your commissions": "تابع عمولاتك",
  "Pay all commissions": "دفع جميع العمولات",
  "No notifications found": "لا توجد إشعارات",
  "typing...": "يكتب الآن...",
  "Hold to talk": "اضغط مع الاستمرار للتحدث",
  "Release to stop": "ارفع لإيقاف التحدث",
  "Connecting…": "جارٍ الاتصال…",
  "Walkie-talkie unavailable": "اللاسلكي غير متاح",
  "on channel": "على القناة",
  "Events Calender": "تقويم الفعاليات",
  "Ratings": "التقييمات",
  "My Shares": "عدد مشاركاتي",
  "My Resume": "السيرة الذاتية",
  "Edit Profile": "تعديل بياناتي",
  "Register Now": "سجل الآن",
  "Days": "أيام",
  "Minutes": "دقائق",
  "Seconds": "ثوانى",
  "Hours": "ساعات",
  "Others": "آخري",
  "Attendance And Departure": "الحضور والانصراف",
  "Chat": "الدردشة",
  "Job Select Error": "إختيار الوظيفة مطلوب!",
  "Period Select Error": "إختيار الفترة مطلوب!",
  'accepted': "تم القبول",
  'initAccept': "قبول مبدئي",
  'pending': "قيد المعالجة",
  'rejected': "مرفوضة",
  "SUCCESS_LOGIN": "تم تسجيل الدخول بنجاح",
  "SEND_REQUEST": "إرسال الطلب",
  "Upcoming": "قادم",
  "Active": "مفعل الان",
  "Finished": "منتهي",
  "Create Evocation": "طلب استئذان",
  "Edit Evocation": "تعديل طلب الاستئذان",
  "Add a new prayer or food evocation": "أضف استئذاناً صلاة أو للطعام",
  "Update evocation details": "تعديل تفاصيل الإستئذان",
  "Details": "التفاصيل",
  "Review": "مراجعة",
  "Evocation Type":"نوع الإستئذان",
  "Duration":"المدة",
  "Notes":"الملاحظات",
  "Review & Confirm":"مراجعة وتأكيد",
  "Events Calendar": "تقويم الفعاليات",
  "Calendar overview": "عرض الفعاليات داخل التقويم",
  "Your personal events": "الفعاليات الخاصة",
  "View past events": "عرض الفعاليات السابقة",
  "Manage your ads": "إدارة الاعلانات",
  "Events & Activities": "الفعاليات & الانشطة",
  "Orders & Processing": "طلبات الإستئذان",
  "Sign out of your account": "تسجيل خروج من حسابك",
  "Track your pending orders": "تابع طلبات الاستئذان",
  "Permissions": "الاستئذانات",
  "Your account has been\ncreated successfully!": "تم إنشاء حسابك بنجاح!",
  "Success!": "نجح!",
  "Welcome to our community!":"أهلاً وسهلاً بك في مجتمع صقر!",
  "Back to Login": "رجوع لتسجيل الدخول",
 "Application Submitted!": "تم تقديم الطلب!",
  "Your job application has been successfully submitted. Please wait for the App Manager's response.": "تم تقديم طلب التوظيف الخاص بك بنجاح. يرجى انتظار رد مدير التطبيق.",
  "Status: Under Review": "الحالة: قيد المراجعة",
  "Expected response: 3-5 business days": "الرد المتوقع: 3-5 أيام عمل",
  "You'll receive updates via email": "ستتلقى التحديثات عبر إشعارات التطبيق",
  "Back to Home": "العودة إلى الصفحة الرئيسية",
  "Confirm Password":"تأكيد كلمة المرور",
  "Confirm Password Required!": "تأكيد كلمة المرور مطلوبة",
  "Full Name": "الاسم ثلاثى",
  "Terms of Use & Privacy Policy": "شروط الإستخدام وحماية الخصوصية",
  "Complete Account": "إستكمال الملف الشخصي",
  "First Name Required!":"الاسم الأول مطلوب",
  "Middle Name Required!": "الاسم الثاني مطلوب",
  "Family Name Required!": "اسم العائلة مطلوب",
  "Conversations": "المحادثات",
  "Experts": "الخبرات السابقة",
  "Previous Events Past": "عدد الفعاليات السابقة",
  "Chronic diseases": "الأمراض المزمنة",
  "Iban File Required":"ملف الايبان مطلوب",
  "Please, agree on terms of Use & Privacy Policy.":"من فضلك، وافق على شروط الاستخدام وسياسة الخصوصية.",
  "Creating Account...": "جاري إنشاء الحساب...",
  "Select your nationality": "إختار الجنسية",
  "Search nationalities...":"بحث...",
  "Select your region": "إختار المنطقة",
  "Search regions...":"بحث...",
  "January": "يناير",
  "February":"فبراير",
  "March": "مارس",
  "April": "إبريل",
  "May": "مايو",
  "June": "يونيو",
  "July": "يوليو",
  "August": "أغسطس",
  "September": "سبتمبر",
  "October": "أكتوبر",
  "November": "نوفمبر",
  "December": "ديسمبر",
  "Year": "سنة",
  "Month": "شهر",
  "Day" : "يوم",
  "National Number Required!":"رقم الهوية إجباري",
  "National ID Should be 10 Digits!": "يجب ان يكون 10 أرقام.",
  "Check In": "تسجيل الدخول للفعالية",
  "No Results Found for Future Events": "لا توجد فعاليات قادمة متاحة",
  "Exit App": "غلق التطبيق",
  "Are you sure you want to exit the app?": "هل أنت متأكد من الخروج من التطبيق؟",
  "Cancel": "إلغاء",
  "Exit": "خروج",
  "Location": "موقع الفعالية",
  "Attendance Reports": "تقرير الحضور والإنصراف",
  "View Details of Attendance and departure": "مشاهدة تفاصيل الحضور والانصراف ",
  "Open Camera to take a profile image": "افتح الكاميرا لالتقاط صورة شخصية",
  "New" : "جديد",
  "Existing": "موجود",
  "Profile Image": "الصورة الشخصية",

  // ---- Chat module ----
  "Chats": "المحادثات",
  "Today": "اليوم",
  "Search chats": "ابحث في المحادثات",
  "No conversations yet": "لا توجد محادثات بعد",
  "No results found": "لا توجد نتائج",
  "Try a different search": "جرّب بحثًا مختلفًا",
  "Start a new chat with the button below": "ابدأ محادثة جديدة بالزر بالأسفل",
  "Tap to start chatting": "اضغط لبدء المحادثة",
  "Yesterday": "أمس",
  "Online": "متصل الآن",
  "participants": "مشارك",
  "Photo": "صورة",
  "Video": "فيديو",
  "Voice message": "رسالة صوتية",
  "Audio": "ملف صوتي",
  "Document": "مستند",
  "You": "أنت",
  "Replying to": "رد على",
  "Unknown": "غير معروف",
  "edited": "تم التعديل",
  "No messages yet": "لا توجد رسائل بعد",
  "Send a message to start the conversation": "أرسل رسالة لبدء المحادثة",
  "Message": "رسالة",
  "Gallery": "المعرض",
  "Contacts": "جهات الاتصال",
  "New Group": "مجموعة جديدة",
  "Search users": "ابحث بالاسم أو البريد أو الهاتف",
  "No contacts yet": "لا توجد جهات اتصال بعد",
  "Search for users to start chatting": "ابحث عن مستخدمين لبدء المحادثة",
  "No users found": "لم يتم العثور على مستخدمين",
  "No ads found": "لا توجد إعلانات",
  "Sign in to continue": "سجّل الدخول للمتابعة",
  "Required": "مطلوب",
  "Send": "إرسال",
  "Error": "خطأ",
  "Failed to play audio": "تعذّر تشغيل الصوت",
  "Create Group": "إنشاء مجموعة",
  "Group Name": "اسم المجموعة",
  "Create": "إنشاء",
  "selected": "محدد",

  // Events redesign — new keys
  "Refresh": "تحديث",
  "Calendar": "التقويم",
  "List": "القائمة",
  "Select a date": "اختر تاريخًا",
  "No events on this day": "لا توجد فعاليات في هذا اليوم",
  "No events scheduled": "لا توجد فعاليات مجدولة",
  "Your events will appear here": "ستظهر فعالياتك هنا",
  "No events found": "لا توجد فعاليات",
  "Event": "فعالية",
  "Live attendance window": "نافذة الحضور المباشرة",
  "Event Location": "موقع الفعالية",
  "Open": "فتح",
  "Submit a leave or permission request": "إرسال طلب إجازة أو استئذان",
  "Walkie Talkie": "اللاسلكي",
  "Attendance": "الحضور",
  "Notifications": "التنبيهات",
  "Check Out": "تسجيل الانصراف",
  "Tap to record your attendance": "اضغط لتسجيل حضورك",
  "Request Permissions": "طلب استئذان",
  "Processing...": "جارٍ المعالجة...",
  "Checked In": "تم تسجيل الحضور",
  "Ready to Check In": "جاهز لتسجيل الحضور",
  "Attendance & Departure": "الحضور والانصراف",

  // Attendance v2 sections
  "Event starts in": "تبدأ الفعالية خلال",
  "Event in progress": "الفعالية جارية الآن",
  "Event ended": "انتهت الفعالية",
  "days": "يوم",
  "hours": "ساعة",
  "minutes": "دقيقة",
  "seconds": "ثانية",
  "Date": "التاريخ",
  "Time": "الوقت",
  "Roles": "الأدوار",
  "Shifts": "الفترات",
  "About": "نبذة",

  // Permissions screen
  "My Permissions": "استئذاناتي",
  "No permissions yet": "لا توجد استئذانات حتى الآن",
  "Submit your first permission request": "أرسل أول طلب استئذان",
  "Note": "ملاحظة",
  "Prayer": "صلاة",
  "Food": "طعام",

  // Application status (pending) screen
  "Application Status": "حالة الطلب",
  "Application under review": "جارٍ مراجعة طلبك",
  "Application rejected": "تم رفض طلبك",
  "This event has not started yet. Attendance may be rejected.": "لم تبدأ الفعالية بعد، وقد يُرفض تسجيل الحضور.",
  "This event has ended. Attendance may be rejected.": "انتهت الفعالية، وقد يُرفض تسجيل الحضور.",
  "The selected zone id is invalid.": "نطاق الفعالية غير مُعرّف على الخادم.",
  "Unable to process your attendance request.": "تعذّر تنفيذ طلب الحضور.",
  "You can now check in when the event starts": "يمكنك تسجيل الحضور عند بدء الفعالية",
  "This application was not approved": "لم تتم الموافقة على هذا الطلب",
  "We'll notify you once a decision is made": "سنعلمك حال صدور القرار",
  "Submitted": "تم الإرسال",
  "Under Review": "قيد المراجعة",
  "Decision": "القرار",

  // Application accepted screen
  "Welcome aboard": "أهلاً بك في الفريق",
  "Application accepted": "تم قبول طلبك",
  "Go to attendance": "الذهاب إلى الحضور",

  // Attendance Report screen
  "Attendance Report": "تقرير الحضور",
  "Total Hours": "إجمالي الساعات",
  "Total Sessions": "عدد الجلسات",
  "On Time": "في الموعد",
  "Late": "متأخر",
  "Events": "الفعاليات",
  "Daily Log": "السجل اليومي",
  "Sessions": "الجلسات",
  "Records": "سجل",
  "Employee ID": "رقم الموظف",
  "Still present": "لا يزال حاضرًا",
  "No attendance records yet": "لا توجد سجلات حضور بعد",

  // ---- Event Apply form ----
  "Apply": "تقديم",
  "Choose role": "اختر الدور",
  "Choose shift": "اختر الفترة",
  "Add a note": "إضافة ملاحظة",
  "Optional": "اختياري",
  "Submit Application": "إرسال الطلب",
  "Submitting...": "جارٍ الإرسال...",
  "No shifts available": "لا توجد فترات متاحة",
  "Terms & Conditions": "الشروط والأحكام",
  "Please read and agree terms and conditions": "من فضلك اقرأ الشروط والأحكام ووافق عليها",
  "Please Confirm your promise": "من فضلك أقرّ بصحة البيانات",
  "Could not load this event. Please try again.": "تعذّر تحميل الفعالية. من فضلك حاول مرة أخرى.",
  "Retry": "إعادة المحاولة",
  "Read more": "اقرأ المزيد",
  "Ad Details": "تفاصيل الإعلان",
  "No walkie-talkie channel has been assigned to this event yet.": "لم يتم تعيين قناة لاسلكي لهذه الفعالية بعد.",
  "Microphone permission is required to use the walkie-talkie. Please enable it in your device settings.": "نحتاج إذن الميكروفون لاستخدام اللاسلكي. من فضلك فعّله من إعدادات جهازك.",
  "Open Settings": "فتح الإعدادات",
  "Channel token is missing.": "رمز القناة غير متوفر.",
  "Could not connect to the channel.": "تعذّر الاتصال بالقناة.",
  "Disconnected from the channel.": "تم قطع الاتصال بالقناة.",
  "Walkie-talkie is not enabled on the server yet.": "خدمة اللاسلكي غير مفعّلة على الخادم بعد.",
  "Could not reach the walkie-talkie server.": "تعذّر الوصول إلى خادم اللاسلكي.",
  "The walkie-talkie server is unavailable.": "خادم اللاسلكي غير متاح.",
  "You are not allowed on this channel.": "غير مصرح لك بدخول هذه القناة.",
  "Could not start the walkie-talkie.": "تعذّر تشغيل اللاسلكي.",
  "Walkie-talkie unavailable — tap to retry": "اللاسلكي غير متاح — اضغط لإعادة المحاولة",
  "Reconnecting...": "جارٍ إعادة الاتصال...",
  "Reconnecting…": "جارٍ إعادة الاتصال…",
  "Could not load this ad": "تعذّر تحميل هذا الإعلان",
  "Could not load advertisements": "تعذّر تحميل الإعلانات",
  "New advertisements will appear here": "ستظهر الإعلانات الجديدة هنا",
  "Server error occurred. Please try again later.": "حدث خطأ في الخادم. من فضلك حاول مرة أخرى لاحقاً.",
  "No internet connection. Please check your network.": "لا يوجد اتصال بالإنترنت. من فضلك تحقق من الشبكة.",
  "Unauthorized access. Please login again.": "غير مصرح لك. من فضلك سجّل الدخول مرة أخرى.",
  "Resource not found.": "العنصر المطلوب غير موجود.",
  "Validation failed.": "تحقق من البيانات المدخلة.",
  "Select the role": "اختر الوظيفة",
  "Write your notes here...": "اكتب ملاحظاتك هنا...",
  "I agree to the Terms & Conditions": "موافق على الشروط والأحكام",
  "I confirm my information is accurate": "أتعهد بصحة البيانات",

  // ---- Event Details screen ----
  "Event Details": "تفاصيل الفعالية",
  "Attachment": "المرفق",
  "View attachment": "عرض المرفق",
  "Open in Maps": "فتح في الخرائط",
  "Show more": "عرض المزيد",
  "Show less": "عرض أقل",
  "Share": "مشاركة",
  "Accept": "أوافق",
  "Reject": "أرفض",
  "OK": "حسناً",

  // Evocation bottom sheet
  "Step": "الخطوة",
  "Previous": "السابق",
  "Update Evocation": "تحديث الاستئذان",
  "Creating evocation": "جارٍ إنشاء الاستئذان",
  "Updating evocation": "جارٍ تحديث الاستئذان",
  "Add any additional notes": "أضف أي ملاحظات إضافية",
  "Enter duration in minutes": "أدخل المدة بالدقائق",
  "Please enter duration": "من فضلك أدخل المدة",
  "Please enter a valid duration": "من فضلك أدخل مدة صحيحة",
  "Duration cannot exceed 24 hours": "المدة لا يجب أن تتجاوز 24 ساعة",
  "Unknown file": "ملف غير معروف",
  "File attached successfully": "تم إرفاق الملف بنجاح",
  "Tap to select file": "اضغط لاختيار ملف",

  // ---- Untranslated strings audit ----
  "( optional ) ": "( اختياري ) ",
  "--": "--",
  "Add image ": "إضافة صورة ",
  "An unexpected error occurred. Please try again.": "حدث خطأ غير متوقع. من فضلك حاول مرة أخرى.",
  "Back to Team Channel": "العودة لقناة الفريق",
  "Bank Account Name Required!": "اسم صاحب الحساب البنكي مطلوب",
  "Camera": "الكاميرا",
  "Category": "التصنيف",
  "Channel": "القناة",
  "Choose Language": "اختر اللغة",
  "Connected": "متصل",
  "Connected Users": "المتصلون",
  "Connecting...": "جارٍ الاتصال...",
  "Continue": "متابعة",
  "Cv File Uploaded": "تم رفع السيرة الذاتية",
  "Description": "الوصف",
  "Disconnected": "غير متصل",
  "Email": "البريد الإلكتروني",
  "Email Required!": "البريد الإلكتروني مطلوب",
  "Error!": "خطأ!",
  "Iban Number Required!": "رقم الآيبان مطلوب",
  "Iban Uploaded": "تم رفع ملف الآيبان",
  "Join Channel": "الانضمام للقناة",
  "Join Supervisors Channel": "الانضمام لقناة المشرفين",
  "Join channel to see users": "انضم للقناة لعرض المتصلين",
  "Leave Channel": "مغادرة القناة",
  "Location Error": "خطأ في تحديد الموقع",
  "Location Restricted": "الموقع مقيّد",
  "Login First": "سجّل الدخول أولاً",
  "Normal Ad": "إعلان عادي",
  "Open Offer": "عرض مفتوح",
  "Password Required!": "كلمة المرور مطلوبة",
  "Passwords do not match": "كلمتا المرور غير متطابقتين",
  "Pay By Card": "الدفع بالبطاقة",
  "Pay By Wallet": "الدفع من المحفظة",
  "Payed": "تم الدفع",
  "Phone": "رقم الجوال",
  "Please select your preferred language": "من فضلك اختر لغتك المفضلة",
  "Premium Ad": "إعلان مميز",
  "Previous Events Calendar": "تقويم الفعاليات السابقة",
  "Previous Events Past Required!": "عدد الفعاليات السابقة مطلوب",
  "Previous Events ii": "الفعاليات السابقة",
  "Price Type": "نوع السعر",
  "Ready to talk": "جاهز للتحدث",
  "Registeration Completed Successfullt": "تم إنشاء الحساب بنجاح",
  "Rejected": "مرفوض",
  "Release to stop talking": "ارفع إصبعك لإيقاف التحدث",
  "Remove Image": "إزالة الصورة",
  "Request Failed": "فشل الطلب",
  "Sagr": "صقر",
  "Send Offer": "إرسال عرض",
  "Show Results": "عرض النتائج",
  "Sold": "تم البيع",
  "Status": "الحالة",
  "Successfully checked in! 🎉": "تم تسجيل حضورك بنجاح! 🎉",
  "Successfully checked out! 👋": "تم تسجيل انصرافك بنجاح! 👋",
  "Title": "العنوان",
  "Transmitting...": "جارٍ الإرسال...",
  "Type": "النوع",
  "Unable to get your current location. Please check your GPS settings and permissions.": "تعذّر تحديد موقعك الحالي. من فضلك تحقق من إعدادات وأذونات الموقع.",
  "Unable to process your attendance request. Please try again.": "تعذّر تنفيذ طلب الحضور. من فضلك حاول مرة أخرى.",
  "Waiting for other users...": "في انتظار انضمام آخرين...",
  "Yes, i'm sure": "نعم، أنا متأكد",
  "You Should Select Minium One Language": "يجب اختيار لغة واحدة على الأقل",
  "You are outside the event zone. You need to be @distance m closer to check in.": "أنت خارج نطاق الفعالية. عليك الاقتراب @distance متر لتسجيل الحضور.",
  "Your message ": "رسالتك ",
  "confirm": "تأكيد",
  "enter_confirm_passowrd": "أعد إدخال كلمة المرور",
  "reset_password": "إعادة تعيين كلمة المرور",
  "save_password": "حفظ كلمة المرور",
  "الدعم": "الدعم",
  "منصة الفعاليات والوظائف": "منصة الفعاليات والوظائف",
  "Could not save your decision. Please try again.": "تعذّر حفظ قرارك. حاول مرة أخرى.",
  "Permission request sent": "تم إرسال طلب الإذن",
  "Permission requests are available once you are assigned to a zone on the event day.": "طلبات الإذن متاحة بعد تعيينك في منطقة يوم الفعالية.",
  "Event details": "تفاصيل الفعالية",
  "Application journey": "مراحل الطلب",
  "Status history": "سجل الحالات",
  "Preliminary acceptance": "القبول المبدئي",
  "Contract decision": "قرارك على العقد",
  "Zone assignment": "تحديد المنطقة",
  "Event day": "يوم الفعالية",
  "Apply now": "قدّم الآن",
  "Apply again": "أعد التقديم",
  "Accept contract": "قبول العقد",
  "Decline": "رفض",
  "View contract": "عرض العقد",
  "Contract": "العقد",
  "Go to check-in": "الذهاب لتسجيل الحضور",
  "Your zone": "منطقتك",
  "Your role": "دورك",
  "Supervisor": "مشرف",
  "Employee": "موظف",
  "Accept the contract?": "قبول العقد؟",
  "Decline the contract?": "رفض العقد؟",
  "Make sure you have read the contract. This decision can't be undone.": "تأكد من قراءة العقد جيدًا، لا يمكن التراجع عن هذا القرار.",
  "Apply for this event": "قدّم على هذه الفعالية",
  "Pick a role and shift, then send your application.": "اختر الوظيفة والفترة ثم أرسل طلبك.",
  "Applications are closed for you on this event.": "لا يمكنك التقديم على هذه الفعالية.",
  "Your application is under review": "طلبك قيد المراجعة",
  "We'll notify you as soon as there's a decision.": "سنرسل لك إشعارًا فور صدور القرار.",
  "You've been preliminarily accepted": "تم قبولك مبدئيًا",
  "Read the contract, then accept or decline it.": "اقرأ العقد ثم اقبله أو ارفضه.",
  "Contract accepted": "تم قبول العقد",
  "The organizer will assign your zone and role soon.": "سيحدد المنظّم منطقتك ودورك قريبًا.",
  "You're all set": "كل شيء جاهز",
  "The event has started": "بدأت الفعالية",
  "Check in from inside your zone to start.": "سجّل حضورك من داخل منطقتك للبدء.",
  "This event has ended": "انتهت هذه الفعالية",
  "You declined the contract": "لقد رفضت العقد",
  "Your application wasn't accepted": "لم يتم قبول طلبك",
  "You can apply to this event again once.": "يمكنك إعادة التقديم على هذه الفعالية مرة واحدة.",
  "You can't apply to this event again.": "لا يمكنك التقديم على هذه الفعالية مرة أخرى.",
  "Waiting for the organizer": "بانتظار المنظّم",
  "Declined": "مرفوض",
  "Not accepted": "لم يُقبل",
  "Could not load the event.": "تعذّر تحميل الفعالية.",
  "You have already applied to this event.": "لقد قدّمت على هذه الفعالية بالفعل.",
  "You can re-apply to an event only once after a rejection.": "يمكنك إعادة التقديم مرة واحدة فقط بعد الرفض.",
  "No application is awaiting your decision for this event.": "لا يوجد طلب بانتظار قرارك على هذه الفعالية.",
  "You are not assigned to this zone for this event today.": "أنت غير معيّن في هذه المنطقة لهذه الفعالية اليوم.",
  "This request has already been reviewed.": "تمت مراجعة هذا الطلب بالفعل.",
  "You have not been assigned to a zone for this event yet.": "لم يتم تعيينك في منطقة لهذه الفعالية بعد.",
  "This event is not running today.": "هذه الفعالية غير قائمة اليوم.",
  "This file could not be displayed here.": "لا يمكن عرض هذا الملف هنا.",
  "Open outside the app": "فتح خارج التطبيق",
  "Try again": "إعادة المحاولة",
  "Could not open this file.": "تعذّر فتح هذا الملف.",
};
