const Map<String, String> ar = {
  "wrraqoon": "وراقون",
  "Home": "الرئيسية",
  "Favorite": "المفضلة",
  "My Orders": "طلباتي",
  "More": "المزيد",
  "login": "تسجيل الدخول",
  "signup": "تسجيل جديد",
  "welcome": "مرحباً",
  'login_first': 'من فضلك، قم بتسجيل الدخول اولا.',
  'forgot_password': "هل نسيت كلمة المرور؟",
  'forgot_password_title': "نسيت كلمة المرور",
  "phone": "رقم الجوال",
  "password": "كلمة المرور",
  "confirm_password": "تأكيد كلمة المرور ",
  "wrong": "حدث خطأ ما، من فضلك حاول مره اخري",
  'phone_or_password_incorrect': "رقم الجوال او كلمة المرور غير صحيحة",
  'enter_phone': 'من فضلك،ادخل رقم الهاتف لإستعادة كلمة المرور.',
  'verification_code': 'التحقق من كود التفعيل',
  'enter_verification_code': 'ادخل كود التفعيل المرسل لرقم الهاتف ',
  'reset_passwors': 'إستعادة كلمة المرور',
  'register': 'تسجيل حساب جديد',
  'enter_your_data': 'ادخل بيانات النموذج لتسجيل الحساب',
  'name': "الاسم",
  'enter_name': 'ادخل الاسم بالكامل ',
  'email': "البريد الإلكتروني",
  'enter_email': 'ادخل البريد الإلكتروني',
  'male': 'ذكر',
  'female': 'انثي',
  'gender': 'النوع',
  "enter_password": "ادخل كلمة المرور",
  'dnot_have_an_account': "لا تمتلك حساب ؟ إنشاء حساب جديد",
  'field_required': "هذا الحقل إجباري",
  "phone_short": "رقم الهاتف يجب الا يقل عن ١٠ ارقام",
  "phone_field_required": "رقم الجوال إجباري!",
  "Create Account": "إنشاء حساب",
  "App Language": "لغة التطبيق",
  "Save Changes": "حفظ التغييرات",
  "Please select the language you want": "من فضلك قم بتحديد اللغة التي تريدها",
  "Shopping Cart": "سلة المشتريات",
  "Order Details": "تفاصيل الطلب",
  "Order Summary": "ملخص الطلب",
  "Checkout": "إتمام الشراء",
  "Total": "الإجمالي",
  "Shipping": "الشحن",
  "Discount": "الخصم",
  "Final Total": "الإجمالي النهائي",
  "Invoice Details": "تفاصيل الفاتورة",
  "Product Details": "تفاصيل المنتج",
  "Product Description": "وصف المنتج",
  "Product Attributes": "مواصفات المنتج",
  "Comments": "التعليقات",
  "Add To Cart": "أضف للسلة",
  "Customers": "العملاء",
  "Points": "النقاط",
  "Settings": "الإعدادات",
  "Points Settings": "إعدادات النقاط",
  "Customer Details": "تفاصيل العميل",
  "Edit Account": "تعديل حسابي",
  "Edit Account Information": "تعديل بيانات الحساب",
  "Logout": "تسجيل الخروج",
  "Success": "نجاح",
  "Success Message": "تم تسجيل الدخول بنجاح",
  "Change Password": "تغيير كلمة المرور",
  'change_password_caption': "قم بغيير كلمة المرور",
  'Confirm': "تأكيد",
  'name_field_required': "الاسم مطلوب",
  'name_short': "الاسم قصيرللغايه",
  "Registeration Completed Successfully": "تم تسجيل الحساب بنجاح",
  'collect': "مستلمة",
  'recover': "مرتجعة",
  "Gifts": "الهدايا",
  'password_short': "كلمة  المرور  قصيرة",
  "Welcome Back": "مرحباً بعودتك",
  "Enter your email and password to sign in to your account":
      "ادخل بزيدك الإلكتروني وكملة المرور \n للدخول لحسابك",
  "Email / Phone Number": "البريد الالكتروني / رقم الهاتف",
  "Password": "كلمة المرور",
  "Remember Me": "تذكرني",
  "Forget password ?": "هل نسيت كلمة المرور؟",
  "OR": "أو",
  "Log in": "تسجيل الدخول",
  "Log in by gmail": "تسجيل الدخول بحساب Gmail",
  "Log in by Apple": "تسجيل الدخول بحساب ابل",
  "Don’t have an account? ": " ليس لديك حساب؟",
  "create account": "إنشاء حساب جديد",
  'today': "To Day",
  "Enter Email or phone": "أدخل البريد الإلكتروني او رقم الهاتف",
  "Field Required": "الحقل إجباري",
  "Already have an account?": "هل لديك حساب بالفعل؟",
  "Login": "تسجيل الدخول",
  "Enter your information to register": "ادخل بيانات لإنشاء حساب جديد",
  "By signing up, I agree with the ": "بالتسجيل، أنا أوافق علي ",
  "Terms of Use  & Privacy Policy": "شروط الاستخدام وسياسة الخصوصية",

  // Create An Account Translations

  "First Name": "الأسم الأول",
  "Middle Name": "الأسم الثاني",
  "Family Name": "أسم العائلة",
  "Bank Account Name": "الاسم كما هو موضح بالحساب البنكي",
  "Phone Number": "رقم الجوال",
  "Iban Number": "رقم الايبان",
  "National Number": "رقم الهوية",
  "Marital Status": "الحالة الإجتماعية",
  "Search Country": "البحث عن الدولة",
  "Select Birth Date": "إختار تاريخ الميلاد",
  "Region": "مكان الاقامة",
  "Education Level": "المستوي الدراسي",
  "Job Status": "الحالة الوظيفية",
  "Languages": "اللغات",
  "Profile": "حسابي",
  "Personal Info": "حسابي",
  "Advertisements": "الإعلانات",
  "Previous Events": "الفعاليات السابقة",
  "My Events": "فعاليتي",
  "Orders Under Processing": "طلبات قيد الاجراء",
  "Events Calender": "تقويم الفعاليات",
  "Ratings": "التقييمات",
  "My Shares": "عدد مشاركاتي",
  "My Resume": "السيرة الذاتية",
  "Edit Profile": "تعديل بياناتي",
  "Register Now": "سجل الآن",
  "Days": "أيام",
  "Minutes": "دقائق",
  "Seconds": "ثوانى",
  "Hours": "ساعات",
  "Others": "آخري",
  "Attendance And Departure": "الحضور والانصراف",
  "Chat": "الدردشة",
  "Job Select Error": "إختيار الوظيفة مطلوب!",
  "Period Select Error": "إختيار الفترة مطلوب!",
  'accepted': "تم القبول",
  'initAccept': "قبول مبدئي",
  'pending': "قيد المعالجة",
  'rejected': "مرفوضة",
  "SUCCESS_LOGIN": "تم تسجيل الدخول بنجاح",
  "SEND_REQUEST": "إسال الطلب",
  "Upcoming": "قادم",
  "Active": "مفعل الان",
  "Finished": "منتهي",
  "Create Evocation": "طلب استئذان",
  "Edit Evocation": "تعديل طلب الاستئذان",
  "Add a new prayer or food evocation": "أضف استئذاناً صلاة أو للطعام",
  "Update evocation details": "تعديل تفاصيل الإستئذان",
  "Details": "التفاصيل",
  "Review": "مراجعة",
  "Evocation Type":"نوع الإستئذان",
  "Duration":"المدة",
  "Notes":"الملاحظات",
  "Review & Confirm":"مراجعة وتأكيد",
  "Events Calendar": "تقويم الفعاليات",
  "Calendar overview": "عرض الفعاليات داخل التقويم",
  "Your personal events": "الفعاليات الخاصة",
  "View past events": "عرض الفعاليات السابقة",
  "Manage your ads": "إدارة الاعلانات",
  "Events & Activities": "الفعاليات & الانشطة",
  "Orders & Processing": "طلبات الإستئذان",
  "Sign out of your account": "تسجيل خروج من حسابك",
  "Track your pending orders": "تابع طلبات الاستئذان",
  "Permissions": "الاستئذانات"


};
