const Map<String, String> en = {
  "wrraqoon":"Wrraqoon",
    "Home":"Home",
  "Favorite":"Favorite",
  "My Orders":"Orders",
  "More":"More",
  "login": "Login",
  "signup": "Sign up",
  "welcome": "Welcome",
  'hassansaeed': "Hassan Saeed",
  'login_first': 'Please, login first and continue',
  'forgot_password': "Forgot password?",
  "phone": "Phone",
  "password": "Password",
  "wrong": "Something went wrong! Please try again",
  'phone_or_password_incorrect': "Phone or password incorrect.",
  'enter_phone': 'من فضلك،ادخل رقم الهاتف لإستعادة كلمة المرور.',
  'verification_code': 'التحقق من كود التفعيل',
  'enter_verification_code': 'ادخل كود التفعيل المرسل لرقم الهاتف ',
  'reset_passwors': 'Reset Password',
  'register': 'Register',
  'enter_your_data': 'Please, enter your personal info.',
  'name': "Name",
  'enter_name': 'Enter your name',
  'email': "E-mail",
  'enter_email': 'Enter your e-mail',
  'male': 'Male',
  'female': 'Female',
  'gender': 'Gender',
  "confirm_password": "Confirm Password",
  "enter_password": "Enter Password",
  'dnot_have_an_account': "Don't have an account? create new",
  'field_required': "الحقل مطلوووووب",
  "App Language": "App Language",
  "Please select the language you want": "Please select the language you want",
  "Save Changes": "Save Changes",
  'today': "Today",

  // ---- Chat module ----
  "Chats": "Chats",
  "Search chats": "Search chats",
  "No conversations yet": "No conversations yet",
  "No results found": "No results found",
  "Try a different search": "Try a different search",
  "Start a new chat with the button below": "Start a new chat with the button below",
  "Tap to start chatting": "Tap to start chatting",
  "Yesterday": "Yesterday",
  "Online": "Online",
  "participants": "participants",
  "Photo": "Photo",
  "Video": "Video",
  "Voice message": "Voice message",
  "Audio": "Audio",
  "Document": "Document",
  "You": "You",
  "Replying to": "Replying to",
  "Unknown": "Unknown",
  "edited": "edited",
  "No messages yet": "No messages yet",
  "Send a message to start the conversation": "Send a message to start the conversation",
  "Message": "Message",
  "Gallery": "Gallery",
  "Contacts": "Contacts",
  "New Group": "New Group",
  "Search users": "Search by name, email or phone",
  "No contacts yet": "No contacts yet",
  "Search for users to start chatting": "Search for users to start chatting",
  "No users found": "No users found",
  "No ads found": "No ads found",
  "Welcome Back": "Welcome Back",
  "Sign in to continue": "Sign in to continue",
  "Required": "Required",
  "password_short": "Password must be at least 6 characters",
  "Cancel": "Cancel",
  "Send": "Send",
  "Error": "Error",
  "Failed to play audio": "Failed to play audio",
  "Create Group": "Create Group",
  "Group Name": "Group name",
  "Create": "Create",
  "selected": "selected",

  // Events redesign — new keys
  "Refresh": "Refresh",
  "Calendar": "Calendar",
  "List": "List",
  "Select a date": "Select a date",
  "No events on this day": "No events on this day",
  "No events scheduled": "No events scheduled",
  "Your events will appear here": "Your events will appear here",
  "No events found": "No events found",
  "Event": "Event",
  "Live attendance window": "Live attendance window",
  "Event Location": "Event Location",
  "Open": "Open",
  "Submit a leave or permission request": "Submit a leave or permission request",
  "Walkie Talkie": "Walkie Talkie",
  "Attendance": "Attendance",
  "Notifications": "Notifications",
  "Check Out": "Check Out",
  "Tap to record your attendance": "Tap to record your attendance",
  "Request Permissions": "Request Permissions",
  "Processing...": "Processing...",
  "Checked In": "Checked In",
  "Ready to Check In": "Ready to Check In",
  "Attendance & Departure": "Attendance & Departure",

  // Attendance v2 sections
  "Event starts in": "Event starts in",
  "Event in progress": "Event in progress",
  "Event ended": "Event ended",
  "days": "days",
  "hours": "hours",
  "minutes": "minutes",
  "seconds": "seconds",
  "Date": "Date",
  "Time": "Time",
  "Roles": "Roles",
  "Shifts": "Shifts",
  "About": "About",

  // Permissions screen
  "Permissions": "Permissions",
  "My Permissions": "My Permissions",
  "No permissions yet": "No permissions yet",
  "Submit your first permission request": "Submit your first permission request",
  "Duration": "Duration",
  "Note": "Note",
  "Prayer": "Prayer",
  "Food": "Food",

  // Application status (pending) screen
  "Application Status": "Application Status",
  "Application under review": "Application under review",
  "We'll notify you once a decision is made":
      "We'll notify you once a decision is made",
  "Submitted": "Submitted",
  "Under Review": "Under Review",
  "Decision": "Decision",

  // Application accepted screen
  "Welcome aboard": "Welcome aboard",
  "Application accepted": "Application accepted",
  "Go to attendance": "Go to attendance",

  // Attendance Report screen
  "Attendance Report": "Attendance Report",
  "Total Hours": "Total Hours",
  "Total Sessions": "Total Sessions",
  "On Time": "On Time",
  "Late": "Late",
  "Events": "Events",
  "Daily Log": "Daily Log",
  "Sessions": "Sessions",
  "Records": "Records",
  "Employee ID": "Employee ID",
  "Still present": "Still present",
  "No attendance records yet": "No attendance records yet",

  // ---- Event Apply form ----
  "Apply": "Apply",
  "Choose role": "Choose role",
  "Choose shift": "Choose shift",
  "Add a note": "Add a note",
  "Optional": "Optional",
  "Submit Application": "Submit Application",
  "Submitting...": "Submitting...",
  "No shifts available": "No shifts available",
  "Terms & Conditions": "Terms & Conditions",

  // ---- Event Details screen ----
  "Event Details": "Event Details",
  "Attachment": "Attachment",
  "View attachment": "View attachment",
  "Open in Maps": "Open in Maps",
  "Show more": "Show more",
  "Show less": "Show less",
  "Share": "Share",
  "Accept": "Accept",
  "Reject": "Reject",
  "OK": "OK",

  // Evocation bottom sheet
  "Step": "Step",
  "Previous": "Previous",
  "Update Evocation": "Update Evocation",
  "Creating evocation": "Creating evocation",
  "Updating evocation": "Updating evocation",
  "Add any additional notes": "Add any additional notes",
  "Enter duration in minutes": "Enter duration in minutes",
  "Please enter duration": "Please enter duration",
  "Please enter a valid duration": "Please enter a valid duration",
  "Duration cannot exceed 24 hours": "Duration cannot exceed 24 hours",
  "Unknown file": "Unknown file",
  "File attached successfully": "File attached successfully",
  "Tap to select file": "Tap to select file"
  //  "phone_short":"رقم الهاتف يجب الا يقل عن ١٠ ارقام"
};
