const Map<String, String> en = {
  "wrraqoon":"Wrraqoon",
    "Home":"Home",
  "Favorite":"Favorite",
  "My Orders":"Orders",
  "More":"More",
  "login": "Login",
  "signup": "Sign up",
  "welcome": "Welcome",
  'hassansaeed': "Hassan Saeed",
  'login_first': 'Please, login first and continue',
  'forgot_password': "Forgot password?",
  "phone": "Phone",
  "password": "Password",
  "wrong": "Something went wrong! Please try again",
  'phone_or_password_incorrect': "Phone or password incorrect.",
  'enter_phone': 'من فضلك،ادخل رقم الهاتف لإستعادة كلمة المرور.',
  'verification_code': 'التحقق من كود التفعيل',
  'enter_verification_code': 'ادخل كود التفعيل المرسل لرقم الهاتف ',
  'reset_passwors': 'Reset Password',
  'register': 'Register',
  'enter_your_data': 'Please, enter your personal info.',
  'name': "Name",
  'enter_name': 'Enter your name',
  'email': "E-mail",
  'enter_email': 'Enter your e-mail',
  'male': 'Male',
  'female': 'Female',
  'gender': 'Gender',
  "confirm_password": "Confirm Password",
  "enter_password": "Enter Password",
  'dnot_have_an_account': "Don't have an account? create new",
  'field_required': "الحقل مطلوووووب",
  "App Language": "App Language",
  "Please select the language you want": "Please select the language you want",
  "Save Changes": "Save Changes",
  'today': "To Day"
  //  "phone_short":"رقم الهاتف يجب الا يقل عن ١٠ ارقام"
};
