const Map<String, String> en = {
  "wrraqoon":"Wrraqoon",
    "Home":"Home",
  "Favorite":"Favorite",
  "My Orders":"Orders",
  "More":"More",
  "login": "Login",
  "signup": "Sign up",
  "welcome": "Welcome",
  'hassansaeed': "Hassan Saeed",
  'login_first': 'Please, login first and continue',
  'forgot_password': "Forgot password?",
  "phone": "Phone",
  "password": "Password",
  "wrong": "Something went wrong! Please try again",
  'phone_or_password_incorrect': "Phone or password incorrect.",
  'enter_phone': 'من فضلك،ادخل رقم الهاتف لإستعادة كلمة المرور.',
  'verification_code': 'التحقق من كود التفعيل',
  'enter_verification_code': 'ادخل كود التفعيل المرسل لرقم الهاتف ',
  'reset_passwors': 'Reset Password',
  'register': 'Register',
  'enter_your_data': 'Please, enter your personal info.',
  'name': "Name",
  'enter_name': 'Enter your name',
  'email': "E-mail",
  'enter_email': 'Enter your e-mail',
  'male': 'Male',
  'female': 'Female',
  'gender': 'Gender',
  "confirm_password": "Confirm Password",
  "enter_password": "Enter Password",
  'dnot_have_an_account': "Don't have an account? create new",
  'field_required': "الحقل مطلوووووب",
  "App Language": "App Language",
  "Please select the language you want": "Please select the language you want",
  "Save Changes": "Save Changes",
  'today': "Today",

  // ---- Chat module ----
  "Chats": "Chats",
  "Search chats": "Search chats",
  "No conversations yet": "No conversations yet",
  "No results found": "No results found",
  "Try a different search": "Try a different search",
  "Start a new chat with the button below": "Start a new chat with the button below",
  "Tap to start chatting": "Tap to start chatting",
  "Yesterday": "Yesterday",
  "Online": "Online",
  "participants": "participants",
  "Photo": "Photo",
  "Video": "Video",
  "Voice message": "Voice message",
  "Audio": "Audio",
  "Document": "Document",
  "You": "You",
  "Replying to": "Replying to",
  "Unknown": "Unknown",
  "edited": "edited",
  "No messages yet": "No messages yet",
  "Send a message to start the conversation": "Send a message to start the conversation",
  "Message": "Message",
  "Gallery": "Gallery",
  "Contacts": "Contacts",
  "New Group": "New Group",
  "Search users": "Search by name, email or phone",
  "No contacts yet": "No contacts yet",
  "Search for users to start chatting": "Search for users to start chatting",
  "No users found": "No users found",
  "No ads found": "No ads found",
  "Welcome Back": "Welcome Back",
  "Sign in to continue": "Sign in to continue",
  "Required": "Required",
  "password_short": "Password must be at least 6 characters",
  "Cancel": "Cancel",
  "Send": "Send",
  "Error": "Error",
  "Failed to play audio": "Failed to play audio",
  "Create Group": "Create Group",
  "Group Name": "Group name",
  "Create": "Create",
  "selected": "selected",

  // Events redesign — new keys
  "Refresh": "Refresh",
  "Calendar": "Calendar",
  "List": "List",
  "Select a date": "Select a date",
  "No events on this day": "No events on this day",
  "No events scheduled": "No events scheduled",
  "Your events will appear here": "Your events will appear here",
  "No events found": "No events found",
  "Event": "Event",
  "Live attendance window": "Live attendance window",
  "Event Location": "Event Location",
  "Open": "Open",
  "Submit a leave or permission request": "Submit a leave or permission request",
  "Walkie Talkie": "Walkie Talkie",
  "Attendance": "Attendance",
  "Notifications": "Notifications",
  "Check Out": "Check Out",
  "Tap to record your attendance": "Tap to record your attendance",
  "Request Permissions": "Request Permissions",
  "Processing...": "Processing...",
  "Checked In": "Checked In",
  "Ready to Check In": "Ready to Check In",
  "Attendance & Departure": "Attendance & Departure",

  // Attendance v2 sections
  "Event starts in": "Event starts in",
  "Event in progress": "Event in progress",
  "Event ended": "Event ended",
  "days": "days",
  "hours": "hours",
  "minutes": "minutes",
  "seconds": "seconds",
  "Date": "Date",
  "Time": "Time",
  "Roles": "Roles",
  "Shifts": "Shifts",
  "About": "About",

  // Permissions screen
  "Permissions": "Permissions",
  "My Permissions": "My Permissions",
  "No permissions yet": "No permissions yet",
  "Submit your first permission request": "Submit your first permission request",
  "Duration": "Duration",
  "Note": "Note",
  "Prayer": "Prayer",
  "Food": "Food",

  // Application status (pending) screen
  "Application Status": "Application Status",
  "Application under review": "Application under review",
  "Application rejected": "Application rejected",
  "This event has not started yet. Attendance may be rejected.": "This event has not started yet. Attendance may be rejected.",
  "This event has ended. Attendance may be rejected.": "This event has ended. Attendance may be rejected.",
  "Unable to process your attendance request.": "Unable to process your attendance request.",
  "You can now check in when the event starts": "You can now check in when the event starts",
  "This application was not approved": "This application was not approved",
  "We'll notify you once a decision is made":
      "We'll notify you once a decision is made",
  "Submitted": "Submitted",
  "Under Review": "Under Review",
  "Decision": "Decision",

  // Application accepted screen
  "Welcome aboard": "Welcome aboard",
  "Application accepted": "Application accepted",
  "Go to attendance": "Go to attendance",

  // Attendance Report screen
  "Attendance Report": "Attendance Report",
  "Total Hours": "Total Hours",
  "Total Sessions": "Total Sessions",
  "On Time": "On Time",
  "Late": "Late",
  "Events": "Events",
  "Daily Log": "Daily Log",
  "Sessions": "Sessions",
  "Records": "Records",
  "Employee ID": "Employee ID",
  "Still present": "Still present",
  "No attendance records yet": "No attendance records yet",

  // ---- Event Apply form ----
  "Apply": "Apply",
  "Choose role": "Choose role",
  "Choose shift": "Choose shift",
  "Add a note": "Add a note",
  "Optional": "Optional",
  "Submit Application": "Submit Application",
  "Submitting...": "Submitting...",
  "No shifts available": "No shifts available",
  "Terms & Conditions": "Terms & Conditions",
  "Please read and agree terms and conditions": "Please read and agree to the terms and conditions",
  "Please Confirm your promise": "Please confirm your information is accurate",
  "Could not load this event. Please try again.": "Could not load this event. Please try again.",
  "Retry": "Retry",
  "Read more": "Read more",
  "Ad Details": "Ad Details",
  "No walkie-talkie channel has been assigned to this event yet.": "No walkie-talkie channel has been assigned to this event yet.",
  "Could not load this ad": "Could not load this ad",
  "Could not load advertisements": "Could not load advertisements",
  "New advertisements will appear here": "New advertisements will appear here",
  "Advertisements": "Advertisements",
  "Server error occurred. Please try again later.": "Server error occurred. Please try again later.",
  "No internet connection. Please check your network.": "No internet connection. Please check your network.",
  "Unauthorized access. Please login again.": "Unauthorized access. Please login again.",
  "Resource not found.": "Resource not found.",
  "Validation failed.": "Validation failed.",
  "Select the role": "Select the role",
  "Write your notes here...": "Write your notes here...",
  "I agree to the Terms & Conditions": "I agree to the Terms & Conditions",
  "I confirm my information is accurate": "I confirm my information is accurate",

  // ---- Event Details screen ----
  "Event Details": "Event Details",
  "Attachment": "Attachment",
  "View attachment": "View attachment",
  "Open in Maps": "Open in Maps",
  "Show more": "Show more",
  "Show less": "Show less",
  "Share": "Share",
  "Accept": "Accept",
  "Reject": "Reject",
  "OK": "OK",

  // Evocation bottom sheet
  "Step": "Step",
  "Previous": "Previous",
  "Update Evocation": "Update Evocation",
  "Creating evocation": "Creating evocation",
  "Updating evocation": "Updating evocation",
  "Add any additional notes": "Add any additional notes",
  "Enter duration in minutes": "Enter duration in minutes",
  "Please enter duration": "Please enter duration",
  "Please enter a valid duration": "Please enter a valid duration",
  "Duration cannot exceed 24 hours": "Duration cannot exceed 24 hours",
  "Unknown file": "Unknown file",
  "File attached successfully": "File attached successfully",
  "Tap to select file": "Tap to select file",
  //  "phone_short":"رقم الهاتف يجب الا يقل عن ١٠ ارقام"

  // ---- Untranslated strings audit ----
  "( optional ) ": "( optional ) ",
  "--": "--",
  "Add image ": "Add image ",
  "An unexpected error occurred. Please try again.": "An unexpected error occurred. Please try again.",
  "Back to Team Channel": "Back to Team Channel",
  "Bank Account Name Required!": "Bank Account Name Required!",
  "Camera": "Camera",
  "Category": "Category",
  "Channel": "Channel",
  "Choose Language": "Choose Language",
  "Connected": "Connected",
  "Connected Users": "Connected Users",
  "Connecting...": "Connecting...",
  "Continue": "Continue",
  "Cv File Uploaded": "Cv File Uploaded",
  "Description": "Description",
  "Disconnected": "Disconnected",
  "Email": "Email",
  "Email Required!": "Email Required!",
  "Error!": "Error!",
  "Iban Number Required!": "Iban Number Required!",
  "Iban Uploaded": "Iban Uploaded",
  "Join Channel": "Join Channel",
  "Join Supervisors Channel": "Join Supervisors Channel",
  "Join channel to see users": "Join channel to see users",
  "Leave Channel": "Leave Channel",
  "Location Error": "Location Error",
  "Location Restricted": "Location Restricted",
  "Login First": "Login First",
  "Normal Ad": "Normal Ad",
  "Open Offer": "Open Offer",
  "Password Required!": "Password Required!",
  "Passwords do not match": "Passwords do not match",
  "Pay By Card": "Pay By Card",
  "Pay By Wallet": "Pay By Wallet",
  "Payed": "Payed",
  "Phone": "Phone",
  "Please select your preferred language": "Please select your preferred language",
  "Premium Ad": "Premium Ad",
  "Previous Events Calendar": "Previous Events Calendar",
  "Previous Events Past Required!": "Previous Events Past Required!",
  "Previous Events ii": "Previous Events ii",
  "Price Type": "Price Type",
  "Ready to talk": "Ready to talk",
  "Registeration Completed Successfullt": "Registeration Completed Successfullt",
  "Rejected": "Rejected",
  "Release to stop talking": "Release to stop talking",
  "Remove Image": "Remove Image",
  "Request Failed": "Request Failed",
  "Sagr": "Sagr",
  "Send Offer": "Send Offer",
  "Show Results": "Show Results",
  "Sold": "Sold",
  "Status": "Status",
  "Successfully checked in! 🎉": "Successfully checked in! 🎉",
  "Successfully checked out! 👋": "Successfully checked out! 👋",
  "Title": "Title",
  "Transmitting...": "Transmitting...",
  "Type": "Type",
  "Unable to get your current location. Please check your GPS settings and permissions.": "Unable to get your current location. Please check your GPS settings and permissions.",
  "Unable to process your attendance request. Please try again.": "Unable to process your attendance request. Please try again.",
  "Waiting for other users...": "Waiting for other users...",
  "Yes, i'm sure": "Yes, i'm sure",
  "You Should Select Minium One Language": "You Should Select Minium One Language",
  "You are outside the event zone. You need to be @distance m closer to check in.": "You are outside the event zone. You need to be @distance m closer to check in.",
  "Your message ": "Your message ",
  "confirm": "confirm",
  "enter_confirm_passowrd": "enter_confirm_passowrd",
  "reset_password": "reset_password",
  "save_password": "save_password",
  "الدعم": "Support",
  "منصة الفعاليات والوظائف": "Events & jobs platform",
  "accepted": "Accepted",
  "initAccept": "Preliminary acceptance",
  "pending": "Under review",
  "rejected": "Rejected",
  "Could not save your decision. Please try again.": "Could not save your decision. Please try again.",
  "Permission request sent": "Permission request sent",
  "Permission requests are available once you are assigned to a zone on the event day.": "Permission requests are available once you are assigned to a zone on the event day.",
  "Event details": "Event details",
  "Application journey": "Application journey",
  "Status history": "Status history",
  "Preliminary acceptance": "Preliminary acceptance",
  "Contract decision": "Contract decision",
  "Zone assignment": "Zone assignment",
  "Event day": "Event day",
  "Apply now": "Apply now",
  "Apply again": "Apply again",
  "Accept contract": "Accept contract",
  "Decline": "Decline",
  "View contract": "View contract",
  "Contract": "Contract",
  "Go to check-in": "Go to check-in",
  "Your zone": "Your zone",
  "Your role": "Your role",
  "Supervisor": "Supervisor",
  "Employee": "Employee",
  "Accept the contract?": "Accept the contract?",
  "Decline the contract?": "Decline the contract?",
  "Make sure you have read the contract. This decision can't be undone.": "Make sure you have read the contract. This decision can't be undone.",
  "Apply for this event": "Apply for this event",
  "Pick a role and shift, then send your application.": "Pick a role and shift, then send your application.",
  "Applications are closed for you on this event.": "Applications are closed for you on this event.",
  "Your application is under review": "Your application is under review",
  "We'll notify you as soon as there's a decision.": "We'll notify you as soon as there's a decision.",
  "You've been preliminarily accepted": "You've been preliminarily accepted",
  "Read the contract, then accept or decline it.": "Read the contract, then accept or decline it.",
  "Contract accepted": "Contract accepted",
  "The organizer will assign your zone and role soon.": "The organizer will assign your zone and role soon.",
  "You're all set": "You're all set",
  "The event has started": "The event has started",
  "Check in from inside your zone to start.": "Check in from inside your zone to start.",
  "This event has ended": "This event has ended",
  "You declined the contract": "You declined the contract",
  "Your application wasn't accepted": "Your application wasn't accepted",
  "You can apply to this event again once.": "You can apply to this event again once.",
  "You can't apply to this event again.": "You can't apply to this event again.",
  "Waiting for the organizer": "Waiting for the organizer",
  "Declined": "Declined",
  "Not accepted": "Not accepted",
  "Could not load the event.": "Could not load the event.",
  "You have already applied to this event.": "You have already applied to this event.",
  "You can re-apply to an event only once after a rejection.": "You can re-apply to an event only once after a rejection.",
  "No application is awaiting your decision for this event.": "No application is awaiting your decision for this event.",
  "You are not assigned to this zone for this event today.": "You are not assigned to this zone for this event today.",
  "This request has already been reviewed.": "This request has already been reviewed.",
  "You have not been assigned to a zone for this event yet.": "You have not been assigned to a zone for this event yet.",
  "This event is not running today.": "This event is not running today.",
  "This file could not be displayed here.": "This file could not be displayed here.",
  "Open outside the app": "Open outside the app",
  "Try again": "Try again",
  "Could not open this file.": "Could not open this file.",
};
